"""Live 12 addressable-target catalogue loader and lookup.

The catalogue is generated by `scripts/build_live12_catalogue.py` from the
upstream `gluon/AbletonLive12_MIDIRemoteScripts` source and lives at
`data/live12_catalogue.json` at the repo root. This module loads that JSON
once, validates it against the published schema (stdlib-only check — see
`_validate_catalogue_shape`), and exposes a `Live12Catalogue` lookup API used
by the Phase 2 output validator.

The catalogue keys are Live's internal device class names (e.g. `Saturator`,
`Eq8`). Each device entry also carries a hand-mapped `displayName` (the Ableton
UI label — e.g. `EQ Eight` for `Eq8`), and `has_device` accepts either form,
case-insensitively. Parameter names are exact-match (Live exposes them
verbatim through its remote-script bank tables); `fuzzy_resolve` provides a
heuristic escape hatch for minor typos.

Static-source extraction does NOT carry `type/min/max/unit/default`. The
`ParamSpec` dataclass has slots for them, and the validator's range gate is
wired but inert when min/max are absent. Reserved for future enrichment from
runtime introspection — see `scripts/build_live12_catalogue.py` extraction
notes.
"""

from __future__ import annotations

import difflib
import json
import re
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any


CATALOGUE_FILENAME = "live12_catalogue.json"

# The canonical catalogue lives at `<repo-root>/data/live12_catalogue.json`.
# This module is at `<repo-root>/apps/backend/live12_catalogue.py`, so two
# parents up gives the repo root.
_REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CATALOGUE_PATH = _REPO_ROOT / "data" / CATALOGUE_FILENAME

_VALID_CATEGORIES = frozenset({"instrument", "audio_effect", "midi_effect", "rack"})
_VALID_PARAM_TYPES = frozenset({"float", "int", "bool", "enum"})
_COMMIT_RE = re.compile(r"^[0-9a-f]{7,40}$")
_FUZZY_MATCH_CUTOFF = 0.7


class CatalogueShapeError(RuntimeError):
    """Raised when the catalogue JSON does not match the published schema."""


@dataclass(frozen=True)
class ParamSpec:
    """Canonical metadata for a Live device parameter.

    `name` is always present. Other fields are optional and currently never
    populated by the static-source generator — they are reserved for future
    enrichment from runtime introspection.
    """

    name: str
    type: str | None = None
    min: float | None = None
    max: float | None = None
    unit: str | None = None
    default: Any = None
    values: tuple[str, ...] | None = None

    def has_range(self) -> bool:
        return self.min is not None and self.max is not None

    def in_range(self, value: float) -> bool:
        """Range-membership check. Caller is responsible for converting Gemini's
        string-typed `value` to a number before calling. Returns True when
        either bound is absent — the gate is inert when range is unknown."""
        if self.min is not None and value < self.min:
            return False
        if self.max is not None and value > self.max:
            return False
        return True


@dataclass(frozen=True)
class DeviceEntry:
    class_name: str
    display_name: str
    category: str
    parameters: tuple[ParamSpec, ...]
    _parameters_by_name: dict[str, ParamSpec]
    _parameter_names: tuple[str, ...]

    def parameter_names(self) -> tuple[str, ...]:
        return self._parameter_names

    def parameter_spec(self, parameter: str) -> ParamSpec | None:
        return self._parameters_by_name.get(parameter)


class Live12Catalogue:
    """Read-only Live 12 device/parameter lookup.

    Build via `Live12Catalogue.load_default()` to get the singleton backed by
    `data/live12_catalogue.json`, or via `Live12Catalogue.from_path(p)` /
    `Live12Catalogue.from_dict(d)` for tests.

    Lookup methods:
        has_device(name)             -- case-insensitive `class` or `displayName`
        has_parameter(d, p)          -- exact-match on canonical parameter name
        parameter_spec(d, p)         -- returns ParamSpec | None
        fuzzy_resolve(d, p)          -- (canonical_device, canonical_parameter) | None
    """

    schema_version: str
    source_commit: str
    source_url: str
    source_files: tuple[str, ...]
    license_note: str
    generated_at: str
    extraction_notes: str
    devices: tuple[DeviceEntry, ...]

    def __init__(
        self,
        *,
        schema_version: str,
        source_commit: str,
        source_url: str,
        source_files: tuple[str, ...],
        license_note: str,
        generated_at: str,
        extraction_notes: str,
        devices: tuple[DeviceEntry, ...],
    ) -> None:
        self.schema_version = schema_version
        self.source_commit = source_commit
        self.source_url = source_url
        self.source_files = source_files
        self.license_note = license_note
        self.generated_at = generated_at
        self.extraction_notes = extraction_notes
        self.devices = devices
        # `_lookup_keys` keys are lowercased class names AND lowercased display
        # names; values are the canonical class name. Display-name aliases let
        # the validator accept both Gemini's UI-name citations ("EQ Eight") and
        # Live's internal class names ("Eq8") without forcing the caller to
        # pick one.
        lookup: dict[str, str] = {}
        for device in devices:
            lookup.setdefault(device.class_name.lower(), device.class_name)
            lookup.setdefault(device.display_name.lower(), device.class_name)
        self._lookup_keys = lookup
        self._devices_by_class = {device.class_name: device for device in devices}

    # ----- construction -----

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Live12Catalogue":
        _validate_catalogue_shape(data)
        devices: list[DeviceEntry] = []
        for raw in data["devices"]:
            params: list[ParamSpec] = []
            for raw_param in raw["parameters"]:
                params.append(_build_param_spec(raw_param))
            param_tuple = tuple(params)
            by_name = {p.name: p for p in param_tuple}
            devices.append(
                DeviceEntry(
                    class_name=raw["class"],
                    display_name=raw["displayName"],
                    category=raw["category"],
                    parameters=param_tuple,
                    _parameters_by_name=by_name,
                    _parameter_names=tuple(p.name for p in param_tuple),
                )
            )
        return cls(
            schema_version=data["schema_version"],
            source_commit=data["source_commit"],
            source_url=data["source_url"],
            source_files=tuple(data["source_files"]),
            license_note=data["license_note"],
            generated_at=data["generated_at"],
            extraction_notes=data["extraction_notes"],
            devices=tuple(devices),
        )

    @classmethod
    def from_path(cls, path: Path | str) -> "Live12Catalogue":
        path = Path(path)
        try:
            text = path.read_text(encoding="utf-8")
        except FileNotFoundError as exc:
            raise CatalogueShapeError(
                f"Live 12 catalogue not found at {path}. "
                f"Run `scripts/build_live12_catalogue.py --source <upstream-clone>`."
            ) from exc
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            raise CatalogueShapeError(
                f"Live 12 catalogue at {path} is not valid JSON: {exc}"
            ) from exc
        return cls.from_dict(data)

    @classmethod
    def load_default(cls) -> "Live12Catalogue":
        return _default_singleton()

    # ----- lookup -----

    def has_device(self, name: str) -> bool:
        if not isinstance(name, str):
            return False
        return name.strip().lower() in self._lookup_keys

    def canonical_device(self, name: str) -> str | None:
        if not isinstance(name, str):
            return None
        return self._lookup_keys.get(name.strip().lower())

    def device(self, name: str) -> DeviceEntry | None:
        canonical = self.canonical_device(name)
        if canonical is None:
            return None
        return self._devices_by_class[canonical]

    def has_parameter(self, device: str, parameter: str) -> bool:
        entry = self.device(device)
        if entry is None:
            return False
        if not isinstance(parameter, str):
            return False
        return parameter in entry._parameters_by_name

    def parameter_spec(self, device: str, parameter: str) -> ParamSpec | None:
        entry = self.device(device)
        if entry is None:
            return None
        if not isinstance(parameter, str):
            return None
        return entry.parameter_spec(parameter)

    def fuzzy_resolve(
        self, device: str, parameter: str
    ) -> tuple[str, str] | None:
        """Heuristic resolution for minor parameter-name typos
        (e.g. `HiCut` -> `High Cut Freq`). Returns (canonical_device,
        canonical_parameter) on a confident match, else None.

        The device side is resolved via the existing case-insensitive
        `class`/`displayName` map (no fuzz). Only the parameter side is
        fuzzy-matched, against the device's known parameter names with a
        difflib cutoff of 0.7. Exact-matches are returned immediately so a
        valid parameter that happens to be close to another name is not
        accidentally rewritten.
        """
        entry = self.device(device)
        if entry is None:
            return None
        if not isinstance(parameter, str):
            return None
        stripped = parameter.strip()
        if not stripped:
            return None
        if stripped in entry._parameters_by_name:
            return (entry.class_name, stripped)
        matches = difflib.get_close_matches(
            stripped,
            entry._parameter_names,
            n=1,
            cutoff=_FUZZY_MATCH_CUTOFF,
        )
        if not matches:
            return None
        return (entry.class_name, matches[0])


# ----- module-level singleton -----

_singleton_lock = threading.Lock()
_singleton: Live12Catalogue | None = None


def _default_singleton() -> Live12Catalogue:
    global _singleton
    if _singleton is not None:
        return _singleton
    with _singleton_lock:
        if _singleton is None:
            _singleton = Live12Catalogue.from_path(DEFAULT_CATALOGUE_PATH)
    return _singleton


def reset_default_singleton_for_tests() -> None:
    """Test-only escape hatch: clear the cached default so a subsequent
    `load_default()` re-reads the on-disk catalogue. Not used by product code."""
    global _singleton
    with _singleton_lock:
        _singleton = None


# ----- schema validation (stdlib-only, structurally matches the JSON Schema) -----

def _validate_catalogue_shape(data: Any) -> None:
    if not isinstance(data, dict):
        raise CatalogueShapeError("Catalogue root must be an object.")

    required_top = (
        "schema_version",
        "source_commit",
        "source_url",
        "source_files",
        "license_note",
        "generated_at",
        "extraction_notes",
        "devices",
    )
    for key in required_top:
        if key not in data:
            raise CatalogueShapeError(f"Catalogue is missing required key '{key}'.")

    if data["schema_version"] != "1":
        raise CatalogueShapeError(
            f"Unsupported catalogue schema_version {data['schema_version']!r}; expected '1'."
        )
    if not isinstance(data["source_commit"], str) or not _COMMIT_RE.match(
        data["source_commit"]
    ):
        raise CatalogueShapeError(
            f"source_commit must be a 7-40 char lowercase hex SHA; got {data['source_commit']!r}."
        )
    for str_key in ("source_url", "license_note", "generated_at", "extraction_notes"):
        value = data[str_key]
        if not isinstance(value, str) or not value:
            raise CatalogueShapeError(f"{str_key} must be a non-empty string.")
    source_files = data["source_files"]
    if (
        not isinstance(source_files, list)
        or not source_files
        or not all(isinstance(p, str) and p for p in source_files)
    ):
        raise CatalogueShapeError(
            "source_files must be a non-empty list of non-empty strings."
        )

    devices = data["devices"]
    if not isinstance(devices, list) or not devices:
        raise CatalogueShapeError("devices must be a non-empty list.")

    seen_classes: set[str] = set()
    for index, raw in enumerate(devices):
        _validate_device_shape(raw, index, seen_classes)


def _validate_device_shape(raw: Any, index: int, seen_classes: set[str]) -> None:
    if not isinstance(raw, dict):
        raise CatalogueShapeError(f"devices[{index}] must be an object.")
    for key in ("class", "category", "displayName", "parameters"):
        if key not in raw:
            raise CatalogueShapeError(f"devices[{index}] missing '{key}'.")
    class_name = raw["class"]
    if not isinstance(class_name, str) or not class_name:
        raise CatalogueShapeError(f"devices[{index}].class must be a non-empty string.")
    if class_name in seen_classes:
        raise CatalogueShapeError(
            f"devices[{index}].class {class_name!r} is duplicated."
        )
    seen_classes.add(class_name)
    if raw["category"] not in _VALID_CATEGORIES:
        raise CatalogueShapeError(
            f"devices[{index}].category {raw['category']!r} not in {sorted(_VALID_CATEGORIES)}."
        )
    display_name = raw["displayName"]
    if not isinstance(display_name, str) or not display_name:
        raise CatalogueShapeError(
            f"devices[{index}].displayName must be a non-empty string."
        )
    parameters = raw["parameters"]
    if not isinstance(parameters, list):
        raise CatalogueShapeError(
            f"devices[{index}].parameters must be a list (may be empty)."
        )
    for p_index, raw_param in enumerate(parameters):
        _validate_parameter_shape(raw_param, index, p_index)


def _validate_parameter_shape(raw: Any, device_index: int, p_index: int) -> None:
    location = f"devices[{device_index}].parameters[{p_index}]"
    if not isinstance(raw, dict):
        raise CatalogueShapeError(f"{location} must be an object.")
    name = raw.get("name")
    if not isinstance(name, str) or not name:
        raise CatalogueShapeError(f"{location}.name must be a non-empty string.")
    if "type" in raw and raw["type"] not in _VALID_PARAM_TYPES:
        raise CatalogueShapeError(
            f"{location}.type {raw['type']!r} not in {sorted(_VALID_PARAM_TYPES)}."
        )
    for numeric in ("min", "max"):
        if numeric in raw and not isinstance(raw[numeric], (int, float)):
            raise CatalogueShapeError(f"{location}.{numeric} must be numeric.")
    if "unit" in raw and not isinstance(raw["unit"], str):
        raise CatalogueShapeError(f"{location}.unit must be a string.")
    if "values" in raw:
        values = raw["values"]
        if not isinstance(values, list) or not all(isinstance(v, str) for v in values):
            raise CatalogueShapeError(f"{location}.values must be a list of strings.")


def _build_param_spec(raw: dict[str, Any]) -> ParamSpec:
    values = raw.get("values")
    return ParamSpec(
        name=raw["name"],
        type=raw.get("type"),
        min=raw.get("min"),
        max=raw.get("max"),
        unit=raw.get("unit"),
        default=raw.get("default"),
        values=tuple(values) if isinstance(values, list) else None,
    )
