"""Live 12 source-catalogue gates that drop or rewrite Phase 2 recommendations.

The Phase 2 Gemini handler emits recommendations as `{device, parameter, value,
phase1Fields}` records inside `mixAndMasterChain`, `abletonRecommendations`,
and `secretSauce.workflowSteps`. The curated `prompts/live12_device_catalog.json`
check in `server_phase2._validate_phase2_catalog_entry` is WARNING-only -- it
flags recommendations whose device or parameter is not in the prompt-side
curated catalog but never drops them.

This module adds a stricter gate backed by the source-extracted
`data/live12_catalogue.json` (generated by `scripts/build_live12_catalogue.py`
from the upstream MIDI Remote Scripts). The contract is:

  1. Reject if `device` is not in the source catalogue.
  2. Reject if `parameter` is not on the device -- but first try
     `Live12Catalogue.fuzzy_resolve`; if it resolves, REWRITE the record's
     `parameter` and emit a structured `PARAMETER_REWRITTEN` event with
     original + resolved + requestId so nothing is rewritten silently.
  3. Reject if numeric `value` falls outside the catalogue range. The gate is
     intentionally inert when `ParamSpec.min/max` are absent because static
     source extraction does not carry ranges; reserved for future enrichment
     from runtime introspection.
  4. Reject if `phase1Fields` is missing or empty. Unresolved cited paths
     (paths that don't resolve against the measurement payload) remain
     WARNING-only via `_validate_phase2_citation_paths`; this gate addresses
     the harder failure of citing nothing at all.

Every rejection emits a structured `RECOMMENDATION_REJECTED` event carrying
`reason`, `device`, `parameter`, `path`, and `requestId`. The function returns
the event list; the caller stitches them into the existing
`validationWarnings` channel. The phase2 result is MUTATED in place to drop
rejected entries -- the goal's "never swallow silently" requirement is met by
the emitted events, not by surviving rejected output.

Living separately from `server_phase2.py` keeps the gate code free of the
FastAPI / pydantic import chain so unit tests can exercise it in pure stdlib.
"""

from __future__ import annotations

import json
import re
from math import isfinite
from typing import Any

from live12_catalogue import Live12Catalogue


_CATALOGUE_REJECT_REASON_DEVICE_UNKNOWN = "device_unknown"
_CATALOGUE_REJECT_REASON_PARAMETER_UNKNOWN = "parameter_unknown"
_CATALOGUE_REJECT_REASON_VALUE_OUT_OF_RANGE = "value_out_of_range"
_CATALOGUE_REJECT_REASON_CITATION_MISSING = "citation_missing"

_VALUE_NUMBER_RE = re.compile(r"-?\d+(?:\.\d+)?")


def _as_record(value: Any) -> dict[str, Any] | None:
    if not value or not isinstance(value, dict):
        return None
    return value


def _stringify_warning_value(value: Any) -> str:
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    except TypeError:
        return str(value)


def _coerce_value_to_number(raw: Any) -> float | None:
    """Pull a finite numeric value out of Gemini's `value` field.

    Gemini emits `value` as a free-form string ("4.5", "-12 dB", "10ms",
    "1:4", "auto"). The range gate only fires when we can extract a single
    finite number; anything ambiguous (compound ratios, slashes, "auto", etc.)
    passes through without a range check rather than producing a false-positive
    rejection.
    """
    if isinstance(raw, bool):  # bool is a subclass of int -- exclude.
        return None
    if isinstance(raw, (int, float)) and isfinite(float(raw)):
        return float(raw)
    if not isinstance(raw, str):
        return None
    if ":" in raw:
        return None  # ratios like "1:4" cannot be one number
    matches = _VALUE_NUMBER_RE.findall(raw)
    if len(matches) != 1:
        return None
    try:
        return float(matches[0])
    except ValueError:
        return None


def _build_recommendation_rejected_event(
    *,
    path: str,
    reason: str,
    message: str,
    device: str,
    parameter: str,
    request_id: str,
    value: Any = None,
) -> dict[str, Any]:
    event: dict[str, Any] = {
        "code": "RECOMMENDATION_REJECTED",
        "path": path,
        "message": message,
        "reason": reason,
        "device": device,
        "parameter": parameter,
        "requestId": request_id,
    }
    if value is not None:
        event["value"] = _stringify_warning_value(value)
    return event


def _build_parameter_rewritten_event(
    *,
    path: str,
    device: str,
    original_parameter: str,
    resolved_parameter: str,
    request_id: str,
) -> dict[str, Any]:
    return {
        "code": "PARAMETER_REWRITTEN",
        "path": path,
        "message": (
            f"Rewrote parameter {original_parameter!r} to "
            f"{resolved_parameter!r} on device {device!r} via Live 12 catalogue "
            "fuzzy resolution."
        ),
        "device": device,
        "originalParameter": original_parameter,
        "resolvedParameter": resolved_parameter,
        "requestId": request_id,
    }


def _catalogue_check_record(
    *,
    catalogue: Live12Catalogue,
    record: dict[str, Any],
    base_path: str,
    request_id: str,
    require_citation: bool,
    events: list[dict[str, Any]],
) -> bool:
    """Run device/parameter/range/citation gates against one record.

    Returns True when the record is accepted (and may have been mutated in
    place by a fuzzy rewrite), False when the record must be dropped.
    Emitted events go onto `events`.
    """
    device_raw = record.get("device")
    parameter_raw = record.get("parameter")
    device = device_raw.strip() if isinstance(device_raw, str) else ""
    parameter = parameter_raw.strip() if isinstance(parameter_raw, str) else ""

    if not catalogue.has_device(device):
        events.append(
            _build_recommendation_rejected_event(
                path=base_path,
                reason=_CATALOGUE_REJECT_REASON_DEVICE_UNKNOWN,
                message=(
                    f"Device {device!r} is not in the Live 12 source catalogue. "
                    "Reject before surfacing the recommendation to the user."
                ),
                device=device,
                parameter=parameter,
                request_id=request_id,
            )
        )
        return False

    canonical_device = catalogue.canonical_device(device) or device
    effective_parameter = parameter

    if not catalogue.has_parameter(canonical_device, parameter):
        resolution = catalogue.fuzzy_resolve(canonical_device, parameter)
        if resolution is None:
            events.append(
                _build_recommendation_rejected_event(
                    path=base_path,
                    reason=_CATALOGUE_REJECT_REASON_PARAMETER_UNKNOWN,
                    message=(
                        f"Parameter {parameter!r} is not on device "
                        f"{canonical_device!r} in the Live 12 source catalogue, "
                        "and fuzzy resolution found no close match."
                    ),
                    device=canonical_device,
                    parameter=parameter,
                    request_id=request_id,
                )
            )
            return False
        resolved_device, resolved_parameter = resolution
        if resolved_parameter != parameter:
            events.append(
                _build_parameter_rewritten_event(
                    path=f"{base_path}.parameter",
                    device=resolved_device,
                    original_parameter=parameter,
                    resolved_parameter=resolved_parameter,
                    request_id=request_id,
                )
            )
            record["parameter"] = resolved_parameter
            effective_parameter = resolved_parameter

    spec = catalogue.parameter_spec(canonical_device, effective_parameter)
    if spec is not None and spec.has_range():
        numeric_value = _coerce_value_to_number(record.get("value"))
        if numeric_value is not None and not spec.in_range(numeric_value):
            events.append(
                _build_recommendation_rejected_event(
                    path=base_path,
                    reason=_CATALOGUE_REJECT_REASON_VALUE_OUT_OF_RANGE,
                    message=(
                        f"Value {numeric_value} for {canonical_device!r}.{effective_parameter!r} "
                        f"is outside the catalogue range [{spec.min}, {spec.max}]."
                    ),
                    device=canonical_device,
                    parameter=effective_parameter,
                    request_id=request_id,
                    value=record.get("value"),
                )
            )
            return False

    if require_citation:
        cited = record.get("phase1Fields")
        non_empty = isinstance(cited, list) and any(
            isinstance(s, str) and s.strip() for s in cited
        )
        if not non_empty:
            events.append(
                _build_recommendation_rejected_event(
                    path=f"{base_path}.phase1Fields",
                    reason=_CATALOGUE_REJECT_REASON_CITATION_MISSING,
                    message=(
                        "Recommendation has no Phase 1 citation. The chain of "
                        "custody invariant requires every Gemini recommendation "
                        "to cite at least one Phase 1 measurement field."
                    ),
                    device=canonical_device,
                    parameter=effective_parameter,
                    request_id=request_id,
                )
            )
            return False

    return True


def _apply_catalogue_gates_to_list(
    *,
    catalogue: Live12Catalogue,
    phase2_result: dict[str, Any],
    list_key: str,
    base_path_prefix: str,
    request_id: str,
    require_citation: bool,
    events: list[dict[str, Any]],
) -> None:
    items = phase2_result.get(list_key)
    if not isinstance(items, list) or not items:
        return
    surviving: list[Any] = []
    for index, item in enumerate(items):
        record = _as_record(item)
        if record is None:
            # Pass through opaque entries -- shape salvage handled them already.
            surviving.append(item)
            continue
        base_path = f"{base_path_prefix}[{index}]"
        if _catalogue_check_record(
            catalogue=catalogue,
            record=record,
            base_path=base_path,
            request_id=request_id,
            require_citation=require_citation,
            events=events,
        ):
            surviving.append(record)
    phase2_result[list_key] = surviving


def _apply_catalogue_gates_to_workflow_steps(
    *,
    catalogue: Live12Catalogue,
    phase2_result: dict[str, Any],
    request_id: str,
    events: list[dict[str, Any]],
) -> None:
    secret_sauce = _as_record(phase2_result.get("secretSauce"))
    if secret_sauce is None:
        return
    steps = secret_sauce.get("workflowSteps")
    if not isinstance(steps, list) or not steps:
        return
    surviving: list[Any] = []
    for index, item in enumerate(steps):
        record = _as_record(item)
        if record is None:
            surviving.append(item)
            continue
        base_path = f"secretSauce.workflowSteps[{index}]"
        # secretSauce workflow steps cite Phase 1 via `phase1Fields` too -- the
        # schema requires the array, so the citation gate applies.
        if _catalogue_check_record(
            catalogue=catalogue,
            record=record,
            base_path=base_path,
            request_id=request_id,
            require_citation=True,
            events=events,
        ):
            surviving.append(record)
    secret_sauce["workflowSteps"] = surviving
    phase2_result["secretSauce"] = secret_sauce


def apply_live12_catalogue_gates(
    phase2_result: dict[str, Any],
    *,
    request_id: str,
    catalogue: Live12Catalogue | None = None,
) -> list[dict[str, Any]]:
    """Mutate `phase2_result` in place, dropping recommendations that fail the
    Live 12 catalogue gates and rewriting parameters resolved via fuzzy match.

    Returns a list of structured events (warning-shaped dicts) describing every
    rejection and rewrite. The caller stitches them into the existing
    `validationWarnings` channel. The mutation is intentional so the
    user-facing payload contains only accepted recommendations.

    The catalogue is loaded from `data/live12_catalogue.json` via
    `Live12Catalogue.load_default()` when not injected explicitly (tests pass a
    test catalogue here).
    """
    if not isinstance(phase2_result, dict):
        return []
    if catalogue is None:
        catalogue = Live12Catalogue.load_default()
    events: list[dict[str, Any]] = []
    # mixAndMasterChain items have a `phase1Fields` array per the schema --
    # citation gate applies. Same for abletonRecommendations.
    _apply_catalogue_gates_to_list(
        catalogue=catalogue,
        phase2_result=phase2_result,
        list_key="mixAndMasterChain",
        base_path_prefix="mixAndMasterChain",
        request_id=request_id,
        require_citation=True,
        events=events,
    )
    _apply_catalogue_gates_to_list(
        catalogue=catalogue,
        phase2_result=phase2_result,
        list_key="abletonRecommendations",
        base_path_prefix="abletonRecommendations",
        request_id=request_id,
        require_citation=True,
        events=events,
    )
    _apply_catalogue_gates_to_workflow_steps(
        catalogue=catalogue,
        phase2_result=phase2_result,
        request_id=request_id,
        events=events,
    )
    return events
